name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4) Lancer les tests
      - name: Run tests
        run: npm test

      # 5) Construire le projet
      - name: Build project
        run: npm run build
