name: CI/CD Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build backend
      - name: Build backend Docker image
        run: docker build -t monuser/backend:latest ./backend

      # Build frontend
      - name: Build frontend Docker image
        run: docker build -t monuser/frontend:latest ./frontend

      # Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push images
      - name: Push backend image
        run: docker push monuser/backend:latest

      - name: Push frontend image
        run: docker push monuser/frontend:latest
